In [23]:
# Question 1: The Vector Conflict - Yes, the similarity score showed that two sentences using the word "light" could still appear similar even when they meant completely different things. This happens because CountVectorizer only counts how many times words appear and does not understand their meaning. Since both sentences contain the word "light", the model assumes there is a relationship between them. As a result, it creates a misleading similarity score even though the contexts are different.
# Question 2: The Context Blindspot - From a Data Science perspective, the Bag-of-Words approach is limited because it ignores the context in which words are used. Search engines and chatbots need to understand the meaning of words to provide accurate results, but static word counts cannot do this. Important information such as word order, context, and semantic meaning is lost during vectorization. This makes it difficult for the system to correctly interpret user queries and conversations.
# Question 3: The GenAI Architectural Fix - Modern Large Language Models like GPT and LLaMA overcome this problem by using Context-Aware Embeddings and Masked Self-Attention. Self-attention helps the model focus on surrounding words to understand the intended meaning of a word within a sentence. Because of this, the word "light" in a sentence about food gets a different vector representation than "light" in a sentence about brightness. This context-based understanding allows LLMs to process language much more accurately than traditional Bag-of-Words methods.

In [24]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

In [25]:
# Load first 50,000 rows

df = pd.read_csv("Reviews.csv", nrows=50000)

print("Dataset Loaded Successfully")
print("Shape :", df.shape)

df.head()

Dataset Loaded Successfully
Shape : (50000, 10)


,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,1303862400,Good Quality Dog Food,I have bought several of the Vitality canned d...
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0,0,1,1346976000,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...
2,3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,1219017600,"""Delight"" says it all",This is a confection that has been around a fe...
3,4,B000UA0QIQ,A395BORC6FGVXV,Karl,3,3,2,1307923200,Cough Medicine,If you are looking for the secret ingredient i...
4,5,B006K2ZZ7K,A1UQRSCLF8GW1T,"Michael D. Bigham ""M. Wassir""",0,0,5,1350777600,Great taffy,Great taffy at a great price. There was a wid...


In [26]:
import pandas as pd

df = pd.read_csv("Reviews.csv", nrows=50000)

print(df.head())
print(df.shape)

   Id   ProductId          UserId                      ProfileName  \
0   1  B001E4KFG0  A3SGXH7AUHU8GW                       delmartian   
1   2  B00813GRG4  A1D87F6ZCVE5NK                           dll pa   
2   3  B000LQOCH0   ABXLMWJIXXAIN  Natalia Corres "Natalia Corres"   
3   4  B000UA0QIQ  A395BORC6FGVXV                             Karl   
4   5  B006K2ZZ7K  A1UQRSCLF8GW1T    Michael D. Bigham "M. Wassir"   

   HelpfulnessNumerator  HelpfulnessDenominator  Score        Time  \
0                     1                       1      5  1303862400   
1                     0                       0      1  1346976000   
2                     1                       1      4  1219017600   
3                     3                       3      2  1307923200   
4                     0                       0      5  1350777600   

                 Summary                                               Text  
0  Good Quality Dog Food  I have bought several of the Vitality canned d...  
1 

In [27]:
light_reviews = df[df["Text"].str.contains("light", case=False, na=False)]

print(light_reviews["Text"].head(50))

2      This is a confection that has been around a fe...
5      I got a wild hair for taffy and ordered this f...
54     I roast at home with a stove-top popcorn poppe...
64     This product serves me well as a source of ele...
94     This is the same food we get at pet store. But...
101    Arrived slightly thawed. My parents wouldn't a...
178    This is not as good as the Frozen Lemon juice,...
189    The coffee is very finely processed and the fl...
221    I've tried a variety of Ahmad tea. Not because...
238    A very delicate green tea with a smooth light ...
246    I love love love this deal - it's way fun to p...
263    I have used and liked Sugar in the Raw for man...
269    This is a delicious sugar. It has a pretty lig...
286    Nothing wrong with the product, but I sure had...
299    I first found Steaz Berry Energy Shots at a lo...
303    I use this product daily, and it provides a st...
304    I've been buying and drinking this for over a ...
327    Even though we are Inter

In [28]:
df.head(50000)

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,1303862400,Good Quality Dog Food,I have bought several of the Vitality canned d...
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0,0,1,1346976000,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...
2,3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,1219017600,"""Delight"" says it all",This is a confection that has been around a fe...
3,4,B000UA0QIQ,A395BORC6FGVXV,Karl,3,3,2,1307923200,Cough Medicine,If you are looking for the secret ingredient i...
4,5,B006K2ZZ7K,A1UQRSCLF8GW1T,"Michael D. Bigham ""M. Wassir""",0,0,5,1350777600,Great taffy,Great taffy at a great price. There was a wid...
...,...,...,...,...,...,...,...,...,...,...
49995,49996,B00430B73W,AKW867T7C6HF8,HWJ3,0,0,5,1261180800,Grown to really like them,My sister introduced me to these. They have be...
49996,49997,B00430B73W,A2PEHNEDMHOYTW,L. Allen,0,0,5,1258934400,Healthy Snack at a great price!,A friend recommended these bars and I fell in ...
49997,49998,B00430B73W,A2QH2KF2IAB143,"J. A. Meyers ""Jan""",0,0,5,1257379200,Raw Revolution Hazelnut Cashew,Fabulous! I take one to work with me every da...
49998,49999,B00430B73W,AMX286UGXISMA,Aaron Dragushan,0,0,4,1247702400,"fantastic, but chew carefully",I love these bars and will continue to buy the...


In [29]:
# Find reviews containing the word 'light'

light_reviews = df[
    df['Text'].str.contains(r'\blight\b', case=False, na=False)
]

print("Number of reviews containing 'light' :")
print(len(light_reviews))

# Display first 20 reviews

for i,text in enumerate(light_reviews['Text'].head(20)):
    print("\n----------------------------")
    print(f"Review {i+1}")
    print(text)

Number of reviews containing 'light' :
1415

----------------------------
Review 1
This is a confection that has been around a few centuries.  It is a light, pillowy citrus gelatin with nuts - in this case Filberts. And it is cut into tiny squares and then liberally coated with powdered sugar.  And it is a tiny mouthful of heaven.  Not too chewy, and very flavorful.  I highly recommend this yummy treat.  If you are familiar with the story of C.S. Lewis' "The Lion, The Witch, and The Wardrobe" - this is the treat that seduces Edmund into selling out his Brother and Sisters to the Witch.

----------------------------
Review 2
A very delicate green tea with a smooth light taste and an subtle floral tones and no bitter aftertaste.<br /><br />In the 20+ years we have been drinking Ahmad teas not even once have we been disappointed. The superb quality of Ahmad teas has remained consistent throughout the years.<br /><br />I am so happy to find Ahmad teas available here (thanks Amazon!) becaus

In [30]:
sentences = [

"This olive oil is wonderful and very light on the stomach.",

"The packaging was broken and let too much light inside the box.",

"I prefer this brand because it is a light and healthy snack."

]

In [31]:
# Initialize CountVectorizer

vectorizer = CountVectorizer()

# Create document-term matrix

X = vectorizer.fit_transform(sentences)

# Convert sparse matrix to dense NumPy array

dense_matrix = X.toarray()

print("Dense Matrix :\n")

print(dense_matrix)

Dense Matrix :

[[1 0 0 0 0 0 0 1 0 0 1 0 1 1 1 0 0 0 1 1 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 0 1 1 1 0 0 0 1 0 0 0 2 0 1 0 1 0]
 [1 1 0 1 0 1 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1 0 0 0 0]]


In [32]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()

matrix = vectorizer.fit_transform(sentences)

In [33]:
print("Vocabulary :")

print(vectorizer.get_feature_names_out())

Vocabulary :
['and' 'because' 'box' 'brand' 'broken' 'healthy' 'inside' 'is' 'it' 'let'
 'light' 'much' 'oil' 'olive' 'on' 'packaging' 'prefer' 'snack' 'stomach'
 'the' 'this' 'too' 'very' 'was' 'wonderful']


In [34]:
vec_1 = dense_matrix[0]

vec_2 = dense_matrix[1]

vec_3 = dense_matrix[2]

print("Vector 1 :")

print(vec_1)

print("\nVector 2 :")

print(vec_2)

print("\nVector 3 :")

print(vec_3)

Vector 1 :
[1 0 0 0 0 0 0 1 0 0 1 0 1 1 1 0 0 0 1 1 1 0 1 0 1]

Vector 2 :
[1 0 1 0 1 0 1 0 0 1 1 1 0 0 0 1 0 0 0 2 0 1 0 1 0]

Vector 3 :
[1 1 0 1 0 1 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1 0 0 0 0]


In [35]:
# Similarity between Sentence 1 and Sentence 2

similarity_1_2 = np.dot(vec_1, vec_2)

# Similarity between Sentence 1 and Sentence 3

similarity_1_3 = np.dot(vec_1, vec_3)

In [36]:
print("="*50)

print("Sentence 1 :")

print(sentences[0])

print("\nSentence 2 :")

print(sentences[1])

print("\nSentence 3 :")

print(sentences[2])

print("\n"+"="*50)

print("Dot Product Similarity")

print("-"*50)

print("Sentence 1 vs Sentence 2 (Different Contexts) :")

print(similarity_1_2)

print("\nSentence 1 vs Sentence 3 (Similar Contexts) :")

print(similarity_1_3)

print("="*50)

Sentence 1 :
This olive oil is wonderful and very light on the stomach.

Sentence 2 :
The packaging was broken and let too much light inside the box.

Sentence 3 :
I prefer this brand because it is a light and healthy snack.

Dot Product Similarity
--------------------------------------------------
Sentence 1 vs Sentence 2 (Different Contexts) :
4

Sentence 1 vs Sentence 3 (Similar Contexts) :
4


In [37]:
!git init
!git config --global user.email "you@example.com"
!git config --global user.name "Your Name"
!git remote add origin <YOUR_GITHUB_REPOSITORY_URL>
!git add .
!git commit -m "MCA Lab: Completed Amazon Review vector analysis and reflection"
!git branch -M main
!git push -u origin main

Reinitialized existing Git repository in /content/.git/
/bin/bash: -c: line 1: syntax error near unexpected token `newline'
/bin/bash: -c: line 1: `git remote add origin <YOUR_GITHUB_REPOSITORY_URL>'
[main caafa99] MCA Lab: Completed Amazon Review vector analysis and reflection
 1 file changed, 185942 insertions(+), 1 deletion(-)
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
